### ISSUE TITLE
Change in UI 

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#13]
change the login and signup component as per design provided in readme.md

**Comment by aritroCoder** [comment]
I have seen the UI samples given at readme file. Do you have the images or icons used in the sample so that I can start with this issue?

**Comment by RupakBiswas-2304** [comment]
> I have seen the UI samples given at readme file. Do you have the images or icons used in the sample so that I can start with this issue?

I have the icon and for image I can ask the designer. I can provide them by tomorrow.

**Comment by RupakBiswas-2304** [comment]
> I have seen the UI samples given at readme file. Do you have the images or icons used in the sample so that I can start with this issue?

Hey , you can select the component and export as png and work with them.

**Comment by padmaja2305** [comment]
I would like to work on this issue
