### ISSUE TITLE
Change in register user api 

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#14]
new register api should take email id, name (first and last) , phone and a file ( any format ..for reference the is a file uploading api in this project check that out for multipart request ) 

you have to store all the details except the file , we have to  hash the file and will store the hash only in data base, no need to salt for now, use SHA-256 .

**Comment by RupakBiswas-2304** [comment]
If you are not sure if you can do it or not , give it a try ..I'll try my best to help.

**Comment by Anurag-ravi** [comment]
i had given it a try,
i changed some fields of User model and implemented the above register functionality
first name,last name,email,phone no,hash     these fields are stored in database
Please let me know if this implementation is as per requirement then i will create a pull request for your consideration,
or something else should be done.

**Comment by RupakBiswas-2304** [comment]
create pr , i'll review
