### ISSUE TITLE
Link the api-doc.md to readme.md

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#15]
Only for new contributor

**Comment by ArchismanKarmakar** [comment]
I am a newbie in open source contribution. but i have created & managed repos in github earlier. I know MERN stack web dev, C, C++. As I am a newbie please assign it to me.

**Comment by ArchismanKarmakar** [comment]
https://github.com/ArchismanKarmakar/File_authentication/blob/main/README.md

**Comment by RupakBiswas-2304** [comment]
create a pr

**Comment by ArchismanKarmakar** [comment]
> create a pr

done sir

**Comment by RupakBiswas-2304** [comment]
Thank you @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
> Thank you @ArchismanKarmakar 

Welcome it was a 1second job sir, i have just finished react so I will work with react projects after doing some projects

**Comment by RupakBiswas-2304** [comment]
> > Thank you @ArchismanKarmakar
> 
> Welcome it was a 1second job sir, i have just finished react so I will work with react projects after doing some projects after making it strong

there are 2 MED taged issue  for react , check them out . They are beginer level ..each of the contains 2 tasks

**Comment by ArchismanKarmakar** [comment]
> > > Thank you @ArchismanKarmakar
> > 
> > Welcome it was a 1second job sir, i have just finished react so I will work with react projects after doing some projects after making it strong
> 
> there are 2 MED taged issue  for react , check them out . They are beginer level ..each of the contains 2 tasks

Okay
