### ISSUE TITLE
Change in Readme.md

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#18]
add a new point in advantage/disadvantage part

**Comment by ArchismanKarmakar** [comment]
i want to work, please assign me

**Comment by RupakBiswas-2304** [comment]
> i want to work, please assign me

create pr

**Comment by ArchismanKarmakar** [comment]
> > i want to work, please assign me
> 
> create pr

done

**Comment by aritroCoder** [comment]
I want to contribute in readme file assign me please

**Comment by RupakBiswas-2304** [comment]
> I want to contribute in readme file assign me please

go ahead , points should be unique

**Comment by aritroCoder** [comment]
I want to add in the readme file please assign me

**Comment by Pana1v** [comment]
I want to contribute to the advantages/disadvantages, And GUI based instructions.

**Comment by RupakBiswas-2304** [comment]
> I want to contribute to the advantages/disadvantages, And GUI based instructions.

go ahead

**Comment by re4lvanshsingh** [comment]
i would like to contribute as well. Please assign me the issue

**Comment by re4lvanshsingh** [comment]
@RupakBiswas-2304 bhaiya could you please assign me this issue.

**Comment by RupakBiswas-2304** [comment]
yes @ggmykppuyy7yup

**Comment by re4lvanshsingh** [comment]
@RupakBiswas-2304 bhaiya i just opened a pull request
