### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#3]
Update necessary changes required  and  correct all typos.

**Comment by geuristic** [comment]
Hi, I'd like to take this up

**Comment by Raeskaa** [comment]
Hi
I'd like to work on this!

**Comment by RupakBiswas-2304** [comment]
Hi @Raeskaa  I'll be the task once coding period starts.
Some details :

**Comment by RupakBiswas-2304** [comment]
> Hi I'd like to work on this!

So, can you add the docs for react js part as well .. then I'll assign you.

**Comment by Raeskaa** [comment]
> > Hi I'd like to work on this!
> 
> So, can you add the docs for react js part as well .. then I'll assign you.

Sure
I'll do it!

**Comment by RupakBiswas-2304** [comment]
@Raeskaa  what is the progress ?

**Comment by Raeskaa** [comment]
> @Raeskaa what is the progress ?

I'm not able to do it
Sorry!

**Comment by RupakBiswas-2304** [comment]
> > @Raeskaa what is the progress ?
> 
> I'm not able to do it Sorry!

If you are stuck somewhere you can ask your doubt in Discord, 
also if you want to give up ,please inform

**Comment by pushkar2112** [comment]
Hey,

I would like to work on this issue. Please confirm that u just want to add the README of the react section to the main project readme?

**Comment by RupakBiswas-2304** [comment]
yes

**Comment by RupakBiswas-2304** [comment]
Thank You @pushkar2112  for contribution
