### ISSUE TITLE
Change in api-doc

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#31]
# Description

As we have a updated login api now , need to change the login part of api-doc

**Comment by re4lvanshsingh** [comment]
@RupakBiswas-2304 can i work on this issue?

**Comment by re4lvanshsingh** [comment]
Bhaiya could you please assign me this?

**Comment by RupakBiswas-2304** [comment]
Yes @re4lvanshsingh  go ahead

**Comment by re4lvanshsingh** [comment]
@RupakBiswas-2304 bhaiya i dont know how i got unassigned. could u assign me again

**Comment by RupakBiswas-2304** [comment]
Don't worry u are assigned or not 
Just create pr ... U are assigned

**Comment by re4lvanshsingh** [comment]
@RupakBiswas-2304 Updated it
