### ISSUE TITLE
Create Api-Doc.md

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#4]
Create Api-Doc.md  and list all existing api end points with demo inputs and outputs

**Comment by RupakBiswas-2304** [comment]
![image](https://user-images.githubusercontent.com/75058161/144372850-88d9da23-b160-4bd0-9a07-971c0f158377.png)

**Comment by HarshBhakkad** [comment]
Where is the list of apis? 
And what is the format for .md file to be created

**Comment by RupakBiswas-2304** [comment]
> Where is the list of apis? And what is the format for .md file to be created

List of apis -> you have to figure it out , there are two urls files where partial urls are there .. 
you have to explore the view also to see the input format
than open postman than put some input and send request , if you get successful response ( as an example see the above screenshot ) .. add the information in Api-Doc.md

format for .md file >  
Endpoint url 
json input
json output
remark if any

**Comment by Anurag-ravi** [comment]
I would like to work on this issue...

**Comment by RupakBiswas-2304** [comment]
Great job @Anurag-ravi
