### ISSUE TITLE
Bug fix in react app 

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#7]
After login using id-password ,
The app should autometically fetch user profile details but this is not working.
In the request it is not sending the jwt cookie back. Need to fix this.

**Comment by RupakBiswas-2304** [comment]
this is issue is worth **15 points**

**Comment by Anurag-ravi** [comment]
I tried to fix this,
it was working only when domain of django and react (both running on localhost not on 127.0.0.1) then it worked fine
will you consider that?

**Comment by RupakBiswas-2304** [comment]
> I tried to fix this, it was working only when domain of django and react (both running on localhost not on 127.0.0.1) then it worked fine will you consider that?

i was running in same host ( but different port )  but now working for me .. can u send the ss ?
ss of profile page

**Comment by Anurag-ravi** [comment]
![image](https://user-images.githubusercontent.com/83827019/145398075-be11bcb2-d54e-4c2b-8939-0f3106cd2d12.png)
