### ISSUE TITLE
A new design

### ISSUE THREAD

**Issue by RupakBiswas-2304** [RupakBiswas-2304/File_authentication#8]
Our final login page will be a form containing an email input and a file input 
same for register page 
so we need a new responsive design. 
create your design in a public figma file and add the link in readme.md

**Comment by pushkar2112** [comment]
Hey, 
Could you please elaborate on how should the login and register page appear. And if you need just the design or u need to implement it too. Also the design should be for web or mobile.

Cheers!

**Comment by RupakBiswas-2304** [comment]
> Hey, Could you please elaborate on how should the login and register page appear. And if you need just the design or u need to implement it too. Also the design should be for web or mobile.
> 
> Cheers!

For this issue we need just the design , implementation would be in the upcoming issues.
Now, about  " how should the login and register page appear " -->
this is a react app so the whole page remains same only components changes, so you have to design component wise,
about what should it contain , for login component > email, a file upload feild, submite button 
same for register component > with some extra feild -> name, phone

also make a good ui , you are free to show your creativity.

**Comment by riyajha2305** [comment]
Can I work on this issue?

**Comment by pushkar2112** [comment]
I would like to solve this issue. Please give the go-ahead for the same.

**Comment by RupakBiswas-2304** [comment]
As @pushkar2112 @riyajha2305 both claimed the issue at almost same time , I m assigning both , but only accept the best one ( also u will be awarded with 5 point ) also if yours are not accepted you would also get 1 point. So start working, please complete it withing 24 hour.

**Comment by riyajha2305** [comment]
Do we need to use images provided under the images folder? Or are we free to use any img of our choice?

**Comment by RupakBiswas-2304** [comment]
you are free to use any image but  no-body should complain copyright.

**Comment by pushkar2112** [comment]
We need just the login and signup page, right?

**Comment by pushkar2112** [comment]
I am done with the prototype where do u want me to submit it, for you to review and suggest any changes that are required?

**Comment by RupakBiswas-2304** [comment]
> I am done with the prototype where do u want me to submit it, for you to review and suggest any changes that are required?

dm me the link in whatsapp 
9774546207

**Comment by riyajha2305** [comment]
I too have made the design. Shall I dm the link to the above given Whatsapp no.?

**Comment by RupakBiswas-2304** [comment]
yeah 

> I too have made the design. Shall I dm the link to the above given Whatsapp no.?


97745****
